[2022-09-01T23:59:02.603-0400] {plugins_manager.py:292} DEBUG - Plugins are already loaded. Skipping.
[2022-09-01T23:59:02.610-0400] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2022-09-01T23:59:02.619-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:59:02.624-0400] {base_task_runner.py:70} DEBUG - Planning to run as the  user
[2022-09-01T23:59:02.628-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> from DB
[2022-09-01T23:59:02.637-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:59:02.637-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2022-09-01T23:59:02.643-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:59:02.643-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2022-09-01T23:59:02.644-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]>
[2022-09-01T23:59:02.644-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:59:02.648-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2022-09-01T23:59:02.650-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:59:02.650-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2022-09-01T23:59:02.652-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [queued]>
[2022-09-01T23:59:02.652-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-01T23:59:02.652-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-01T23:59:02.652-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-01T23:59:02.665-0400] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): curate_yahoo_finance_html> on 2022-09-02 03:58:49.928251+00:00
[2022-09-01T23:59:02.667-0400] {standard_task_runner.py:52} INFO - Started process 19826 to run task
[2022-09-01T23:59:02.674-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl', 'curate_yahoo_finance_html', 'manual__2022-09-02T03:58:49.928251+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmp2zgvydvf', '--error-file', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmp84apl4md']
[2022-09-01T23:59:02.676-0400] {standard_task_runner.py:80} INFO - Job 32: Subtask curate_yahoo_finance_html
[2022-09-01T23:59:02.681-0400] {cli_action_loggers.py:66} DEBUG - Calling callbacks: [<function default_action_log at 0x7fe65f3283a0>]
[2022-09-01T23:59:02.696-0400] {settings.py:398} DEBUG - Disposing DB connection pool (PID 19826)
[2022-09-01T23:59:02.697-0400] {settings.py:260} DEBUG - Setting up DB connection pool (PID 19826)
[2022-09-01T23:59:02.698-0400] {settings.py:330} DEBUG - settings.prepare_engine_args(): Using NullPool
[2022-09-01T23:59:02.734-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:59:02.742-0400] {task_command.py:371} INFO - Running <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [running]> on host FAS-EALC-LIU-2
[2022-09-01T23:59:02.743-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [running]> from DB
[2022-09-01T23:59:02.768-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:59:02.772-0400] {taskinstance.py:943} DEBUG - Clearing XCom data
[2022-09-01T23:59:02.832-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_etl
AIRFLOW_CTX_TASK_ID=curate_yahoo_finance_html
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T03:58:49.928251+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-02T03:58:49.928251+00:00
[2022-09-01T23:59:02.833-0400] {__init__.py:146} DEBUG - Preparing lineage inlets and outlets
[2022-09-01T23:59:02.833-0400] {__init__.py:190} DEBUG - inlets: [], outlets: []
[2022-09-01T23:59:03.076-0400] {logging_mixin.py:115} INFO - 
Market price:  126.42 
After hours trading price:  126.41
[2022-09-01T23:59:03.077-0400] {python.py:173} INFO - Done. Returned value was: (<fin-streamer active="" class="Fw(b) Fz(36px) Mb(-4px) D(ib)" data-field="regularMarketPrice" data-pricehint="2" data-symbol="TROW" data-test="qsp-price" data-trend="none" value="126.42">126.42</fin-streamer>, <fin-streamer active="" class="C($primaryColor) Fz(24px) Fw(b)" data-field="postMarketPrice" data-pricehint="2" data-symbol="TROW" data-test="qsp-price" data-trend="none" value="126.41">126.41</fin-streamer>)
[2022-09-01T23:59:03.083-0400] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2398, in xcom_push
    XCom.set(
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/models/xcom.py", line 192, in set
    value = cls.serialize_value(
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/models/xcom.py", line 581, in serialize_value
    return pickle.dumps(value)
RecursionError: maximum recursion depth exceeded while pickling an object
[2022-09-01T23:59:03.090-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [running]> from DB
[2022-09-01T23:59:03.094-0400] {taskinstance.py:2349} DEBUG - Task Duration set to 0.449915
[2022-09-01T23:59:03.095-0400] {taskinstance.py:1418} DEBUG - Clearing next_method and next_kwargs.
[2022-09-01T23:59:03.096-0400] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=test_etl, task_id=curate_yahoo_finance_html, execution_date=20220902T035849, start_date=20220902T035902, end_date=20220902T035903
[2022-09-01T23:59:03.110-0400] {cli_action_loggers.py:84} DEBUG - Calling callbacks: []
[2022-09-01T23:59:03.111-0400] {standard_task_runner.py:92} ERROR - Failed to execute job 32 for task curate_yahoo_finance_html (maximum recursion depth exceeded while pickling an object; 19826)
[2022-09-01T23:59:03.157-0400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-01T23:59:03.158-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:58:49.928251+00:00 [running]> from DB
[2022-09-01T23:59:03.190-0400] {dagrun.py:642} DEBUG - number of tis tasks for <DagRun test_etl @ 2022-09-02 03:58:49.928251+00:00: manual__2022-09-02T03:58:49.928251+00:00, state:running, queued_at: 2022-09-02 03:58:49.944068+00:00. externally triggered: True>: 3 task(s)
[2022-09-01T23:59:03.190-0400] {dagrun.py:666} DEBUG - number of scheduleable tasks for <DagRun test_etl @ 2022-09-02 03:58:49.928251+00:00: manual__2022-09-02T03:58:49.928251+00:00, state:running, queued_at: 2022-09-02 03:58:49.944068+00:00. externally triggered: True>: 1 task(s)
[2022-09-01T23:59:03.191-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:58:49.928251+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:59:03.191-0400] {taskinstance.py:970} DEBUG - Setting task state for <TaskInstance: test_etl.generate_report manual__2022-09-02T03:58:49.928251+00:00 [None]> to upstream_failed
[2022-09-01T23:59:03.191-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:58:49.928251+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 2, 'successes': 1, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 2}, upstream_task_ids={'curate_yahoo_finance_html', 'hit_wikipedia_api'}
[2022-09-01T23:59:03.192-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.generate_report manual__2022-09-02T03:58:49.928251+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 2, 'successes': 1, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 2}, upstream_task_ids={'curate_yahoo_finance_html', 'hit_wikipedia_api'}
[2022-09-01T23:59:03.192-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:58:49.928251+00:00 [upstream_failed]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:59:03.203-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
