[2022-09-01T23:49:22.519-0400] {plugins_manager.py:292} DEBUG - Plugins are already loaded. Skipping.
[2022-09-01T23:49:22.526-0400] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2022-09-01T23:49:22.537-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:49:22.541-0400] {base_task_runner.py:70} DEBUG - Planning to run as the  user
[2022-09-01T23:49:22.545-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> from DB
[2022-09-01T23:49:22.555-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:22.555-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2022-09-01T23:49:22.556-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:49:22.563-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2022-09-01T23:49:22.564-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2022-09-01T23:49:22.564-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]>
[2022-09-01T23:49:22.564-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:22.567-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:49:22.567-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2022-09-01T23:49:22.569-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2022-09-01T23:49:22.574-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2022-09-01T23:49:22.574-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [queued]>
[2022-09-01T23:49:22.574-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-01T23:49:22.574-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 4
[2022-09-01T23:49:22.574-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-01T23:49:22.590-0400] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): hit_wikipedia_api> on 2022-09-02 03:49:13.195465+00:00
[2022-09-01T23:49:22.603-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl', 'hit_wikipedia_api', 'manual__2022-09-02T03:49:13.195465+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmpzb7nyzfu', '--error-file', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmp15qsjdn1']
[2022-09-01T23:49:22.606-0400] {standard_task_runner.py:80} INFO - Job 25: Subtask hit_wikipedia_api
[2022-09-01T23:49:22.613-0400] {cli_action_loggers.py:66} DEBUG - Calling callbacks: [<function default_action_log at 0x7f89484393a0>]
[2022-09-01T23:49:22.592-0400] {standard_task_runner.py:52} INFO - Started process 19322 to run task
[2022-09-01T23:49:22.633-0400] {settings.py:398} DEBUG - Disposing DB connection pool (PID 19322)
[2022-09-01T23:49:22.635-0400] {settings.py:260} DEBUG - Setting up DB connection pool (PID 19322)
[2022-09-01T23:49:22.636-0400] {settings.py:330} DEBUG - settings.prepare_engine_args(): Using NullPool
[2022-09-01T23:49:22.689-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:49:22.698-0400] {task_command.py:371} INFO - Running <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [running]> on host FAS-EALC-LIU-2
[2022-09-01T23:49:22.699-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [running]> from DB
[2022-09-01T23:49:22.730-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:49:22.734-0400] {taskinstance.py:943} DEBUG - Clearing XCom data
[2022-09-01T23:49:22.772-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_etl
AIRFLOW_CTX_TASK_ID=hit_wikipedia_api
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T03:49:13.195465+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-02T03:49:13.195465+00:00
[2022-09-01T23:49:22.773-0400] {__init__.py:146} DEBUG - Preparing lineage inlets and outlets
[2022-09-01T23:49:22.774-0400] {__init__.py:190} DEBUG - inlets: [], outlets: []
[2022-09-01T23:49:22.889-0400] {python.py:173} INFO - Done. Returned value was: T. Rowe Price (id: 3990635, ns: 0)
[2022-09-01T23:49:22.893-0400] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2022-09-01T23:49:22.894-0400] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2398, in xcom_push
    XCom.set(
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/models/xcom.py", line 192, in set
    value = cls.serialize_value(
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WikipediaPage is not JSON serializable
[2022-09-01T23:49:22.901-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [running]> from DB
[2022-09-01T23:49:22.904-0400] {taskinstance.py:2349} DEBUG - Task Duration set to 0.340501
[2022-09-01T23:49:22.906-0400] {taskinstance.py:1418} DEBUG - Clearing next_method and next_kwargs.
[2022-09-01T23:49:22.906-0400] {taskinstance.py:1407} INFO - Marking task as UP_FOR_RETRY. dag_id=test_etl, task_id=hit_wikipedia_api, execution_date=20220902T034913, start_date=20220902T034922, end_date=20220902T034922
[2022-09-01T23:49:22.916-0400] {cli_action_loggers.py:84} DEBUG - Calling callbacks: []
[2022-09-01T23:49:22.916-0400] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task hit_wikipedia_api (Object of type WikipediaPage is not JSON serializable; 19322)
[2022-09-01T23:49:22.954-0400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-01T23:49:22.955-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [running]> from DB
[2022-09-01T23:49:22.979-0400] {dagrun.py:642} DEBUG - number of tis tasks for <DagRun test_etl @ 2022-09-02 03:49:13.195465+00:00: manual__2022-09-02T03:49:13.195465+00:00, state:running, queued_at: 2022-09-02 03:49:13.214385+00:00. externally triggered: True>: 3 task(s)
[2022-09-01T23:49:22.980-0400] {dagrun.py:666} DEBUG - number of scheduleable tasks for <DagRun test_etl @ 2022-09-02 03:49:13.195465+00:00: manual__2022-09-02T03:49:13.195465+00:00, state:running, queued_at: 2022-09-02 03:49:13.214385+00:00. externally triggered: True>: 2 task(s)
[2022-09-01T23:49:22.980-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:22.980-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:49:22.980-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_tasks_state={'total': 2, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html'}
[2022-09-01T23:49:22.981-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_tasks_state={'total': 2, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html'}
[2022-09-01T23:49:22.981-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:22.981-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2022-09-02T03:49:22.981409+00:00 and task will be retried at 2022-09-02T03:57:02.904925+00:00.
[2022-09-01T23:49:22.981-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2022-09-02T03:49:22.981409+00:00 and task will be retried at 2022-09-02T03:57:02.904925+00:00.
[2022-09-01T23:49:22.981-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2022-09-01T23:49:22.987-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
