[2022-09-01T23:49:29.378-0400] {plugins_manager.py:292} DEBUG - Plugins are already loaded. Skipping.
[2022-09-01T23:49:29.385-0400] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2022-09-01T23:49:29.395-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:49:29.399-0400] {base_task_runner.py:70} DEBUG - Planning to run as the  user
[2022-09-01T23:49:29.403-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> from DB
[2022-09-01T23:49:29.412-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2022-09-01T23:49:29.412-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:49:29.418-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:29.419-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2022-09-01T23:49:29.419-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]>
[2022-09-01T23:49:29.419-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:49:29.420-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2022-09-01T23:49:29.421-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:29.425-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2022-09-01T23:49:29.427-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [queued]>
[2022-09-01T23:49:29.428-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-01T23:49:29.428-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-01T23:49:29.428-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-01T23:49:29.443-0400] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): curate_yahoo_finance_html> on 2022-09-02 03:49:13.195465+00:00
[2022-09-01T23:49:29.445-0400] {standard_task_runner.py:52} INFO - Started process 19335 to run task
[2022-09-01T23:49:29.452-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl', 'curate_yahoo_finance_html', 'manual__2022-09-02T03:49:13.195465+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmpm4wzgd5k', '--error-file', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmp6j901ed_']
[2022-09-01T23:49:29.454-0400] {standard_task_runner.py:80} INFO - Job 26: Subtask curate_yahoo_finance_html
[2022-09-01T23:49:29.459-0400] {cli_action_loggers.py:66} DEBUG - Calling callbacks: [<function default_action_log at 0x7fe23db293a0>]
[2022-09-01T23:49:29.474-0400] {settings.py:398} DEBUG - Disposing DB connection pool (PID 19335)
[2022-09-01T23:49:29.475-0400] {settings.py:260} DEBUG - Setting up DB connection pool (PID 19335)
[2022-09-01T23:49:29.475-0400] {settings.py:330} DEBUG - settings.prepare_engine_args(): Using NullPool
[2022-09-01T23:49:29.512-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:49:29.522-0400] {task_command.py:371} INFO - Running <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [running]> on host FAS-EALC-LIU-2
[2022-09-01T23:49:29.524-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [running]> from DB
[2022-09-01T23:49:29.546-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-01T23:49:29.549-0400] {taskinstance.py:943} DEBUG - Clearing XCom data
[2022-09-01T23:49:29.646-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_etl
AIRFLOW_CTX_TASK_ID=curate_yahoo_finance_html
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T03:49:13.195465+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-02T03:49:13.195465+00:00
[2022-09-01T23:49:29.647-0400] {__init__.py:146} DEBUG - Preparing lineage inlets and outlets
[2022-09-01T23:49:29.648-0400] {__init__.py:190} DEBUG - inlets: [], outlets: []
[2022-09-01T23:49:29.860-0400] {logging_mixin.py:115} INFO - 
Market price:  126.42 
After hours trading price:  126.41
[2022-09-01T23:49:29.861-0400] {python.py:173} INFO - Done. Returned value was: (<fin-streamer active="" class="Fw(b) Fz(36px) Mb(-4px) D(ib)" data-field="regularMarketPrice" data-pricehint="2" data-symbol="TROW" data-test="qsp-price" data-trend="none" value="126.42">126.42</fin-streamer>, <fin-streamer active="" class="C($primaryColor) Fz(24px) Fw(b)" data-field="postMarketPrice" data-pricehint="2" data-symbol="TROW" data-test="qsp-price" data-trend="none" value="126.41">126.41</fin-streamer>)
[2022-09-01T23:49:29.861-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [running]> from DB
[2022-09-01T23:49:29.869-0400] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 180, in execute
    return self._handle_output(return_value=return_value, context=context, xcom_push=self.xcom_push)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 202, in _handle_output
    raise AirflowException(
airflow.exceptions.AirflowException: Returned output was type <class 'tuple'> expected dictionary for multiple_outputs
[2022-09-01T23:49:29.871-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [running]> from DB
[2022-09-01T23:49:29.873-0400] {taskinstance.py:2349} DEBUG - Task Duration set to 0.453996
[2022-09-01T23:49:29.874-0400] {taskinstance.py:1418} DEBUG - Clearing next_method and next_kwargs.
[2022-09-01T23:49:29.875-0400] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=test_etl, task_id=curate_yahoo_finance_html, execution_date=20220902T034913, start_date=20220902T034929, end_date=20220902T034929
[2022-09-01T23:49:29.888-0400] {cli_action_loggers.py:84} DEBUG - Calling callbacks: []
[2022-09-01T23:49:29.890-0400] {standard_task_runner.py:92} ERROR - Failed to execute job 26 for task curate_yahoo_finance_html (Returned output was type <class 'tuple'> expected dictionary for multiple_outputs; 19335)
[2022-09-01T23:49:29.939-0400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-01T23:49:29.940-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-02T03:49:13.195465+00:00 [running]> from DB
[2022-09-01T23:49:29.970-0400] {dagrun.py:642} DEBUG - number of tis tasks for <DagRun test_etl @ 2022-09-02 03:49:13.195465+00:00: manual__2022-09-02T03:49:13.195465+00:00, state:running, queued_at: 2022-09-02 03:49:13.214385+00:00. externally triggered: True>: 3 task(s)
[2022-09-01T23:49:29.971-0400] {dagrun.py:666} DEBUG - number of scheduleable tasks for <DagRun test_etl @ 2022-09-02 03:49:13.195465+00:00: manual__2022-09-02T03:49:13.195465+00:00, state:running, queued_at: 2022-09-02 03:49:13.214385+00:00. externally triggered: True>: 2 task(s)
[2022-09-01T23:49:29.971-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-01T23:49:29.971-0400] {taskinstance.py:970} DEBUG - Setting task state for <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [None]> to upstream_failed
[2022-09-01T23:49:29.972-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_tasks_state={'total': 2, 'successes': 0, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 1}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html'}
[2022-09-01T23:49:29.972-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_tasks_state={'total': 2, 'successes': 0, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 1}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html'}
[2022-09-01T23:49:29.972-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-02T03:49:13.195465+00:00 [upstream_failed]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:29.972-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2022-09-02T03:49:29.972611+00:00 and task will be retried at 2022-09-02T03:57:02.904925+00:00.
[2022-09-01T23:49:29.972-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2022-09-02T03:49:29.972611+00:00 and task will be retried at 2022-09-02T03:57:02.904925+00:00.
[2022-09-01T23:49:29.973-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2022-09-01T23:49:29.973-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.hit_wikipedia_api manual__2022-09-02T03:49:13.195465+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-01T23:49:29.982-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
