[2022-08-30T19:59:56.222-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-30T23:59:48.123951+00:00 [queued]>
[2022-08-30T19:59:56.241-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-30T23:59:48.123951+00:00 [queued]>
[2022-08-30T19:59:56.242-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-30T19:59:56.242-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-08-30T19:59:56.242-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-30T19:59:56.258-0400] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): curate_yahoo_finance_html> on 2022-08-30 23:59:48.123951+00:00
[2022-08-30T19:59:56.260-0400] {standard_task_runner.py:52} INFO - Started process 8282 to run task
[2022-08-30T19:59:56.272-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl', 'curate_yahoo_finance_html', 'manual__2022-08-30T23:59:48.123951+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmpsii0g_v8', '--error-file', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmpbu9vqx0g']
[2022-08-30T19:59:56.278-0400] {standard_task_runner.py:80} INFO - Job 10: Subtask curate_yahoo_finance_html
[2022-08-30T19:59:56.367-0400] {task_command.py:371} INFO - Running <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-30T23:59:48.123951+00:00 [running]> on host FAS-EALC-LIU-2
[2022-08-30T19:59:56.446-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_etl
AIRFLOW_CTX_TASK_ID=curate_yahoo_finance_html
AIRFLOW_CTX_EXECUTION_DATE=2022-08-30T23:59:48.123951+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-30T23:59:48.123951+00:00
[2022-08-30T19:59:56.589-0400] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/airflow/dags/test_dag.py", line 49, in curate_yahoo_finance_html
    soup = BeautifulSoup(yahoo_finance_page.text, 'html.parser')
AttributeError: 'int' object has no attribute 'text'
[2022-08-30T19:59:56.596-0400] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=test_etl, task_id=curate_yahoo_finance_html, execution_date=20220830T235948, start_date=20220830T235956, end_date=20220830T235956
[2022-08-30T19:59:56.606-0400] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task curate_yahoo_finance_html ('int' object has no attribute 'text'; 8282)
[2022-08-30T19:59:56.640-0400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-30T19:59:56.667-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
